# Generated by Django 6.0.5 on 2026-05-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(max_length=150)),
                ('device_type', models.CharField(choices=[('computer', 'Computer'), ('phone', 'Phone'), ('printer', 'Printer'), ('wifi', 'Wi-Fi / Network'), ('email', 'Email / Account'), ('smart_device', 'Smart TV / Camera / Device'), ('business_it', 'Small Business IT'), ('other', 'Other')], max_length=50)),
                ('issue_description', models.TextField()),
                ('best_time_to_contact', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
